# Site
name: "Tessa Goh"
title: "Tessa Goh"
description: " 👋 Hi! I'm Tessa. \n\n I'm a UX designer, currently based in Singapore."
logo: 'assets/images/logo.svg'
favicon: 'assets/images/logo.png'
baseurl: ""
google_analytics: 'UA-xxxxxxxx-1'
disqus: 'demowebsite'
# mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/
email: tessagsy@gmail.com

# Authors
authors:
  tessa:
    name: Tessa
    display_name: tgsy
    avatar: 'assets/images/avatar-tessa.jpg'
    email: tessagsy@gmail.com
    # web: https://www.wowthemes.net/donate/
    # twitter: https://twitter.com/wowthemesnet
    description: "UX Designer, based in Singapore."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "disabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
